gui:
  theme: # catppuccin palette of course
    selectedLineBgColor:
      - "black"

  authorColors:
    "*": "#b4befe"
  showBottomLine: false
  border: single
  nerdFontsVersion: "3"

os:
  editPreset: "nvim-remote"
promptToReturnFromSubprocess: false
keybinding:
  universal:
    quit: Q
    scrollUpMain: <c-k>
    scrollDownMain: <c-j>
  commits:
    moveDownCommit: <c-x>
    moveUpCommit: <c-w>
