gui:
  theme: # catppuccin palette of course
    selectedLineBgColor:
      - "#6272A4"

  authorColors:
    "*": "#b4befe"
  showBottomLine: false
  border: single
  nerdFontsVersion: "3"
  spiner:
    frames:
      - ⣾
      - ⣽
      - ⣻
      - ⢿
      - ⡿
      - ⣟
      - ⣯
      - ⣷

os:
  editPreset: "nvim-remote"
promptToReturnFromSubprocess: false
keybinding:
  universal:
    quit: Q
  commits:
    moveDownCommit: <c-x>
    moveUpCommit: <c-w>
